# This workflow is run manually.
# It simulates a phase where we would run E2E tests and on success merge
# the trunk to the staging branch. It will also bump the version in the
# 'version' file with a new commit.

name: Merge to staging

on: workflow_dispatch

jobs:
  merge_to_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0
      - id: run_tests
        run: |
          echo Tests OK
          echo ::set-output name=testOutput::pass
      - name: Merge trunk to staging and commit updated version file
        if: steps.run_tests.outputs.testOutput == 'pass'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "RGS merge bot"
          git config user.email rgs@consttype.org
          git fetch origin trunk
          git merge origin/trunk || exit 1
          if [ -f version ];
          then
            new_version=$(perl -lpe 's/\.\K([0-9]+).*/1+$1/e' version)
            echo $new_version.0 > version
            git add version
            git commit -m 'Update version file'
            git push
          fi
