# This workflow is run manually.
# It simulates a phase where we would run E2E tests and on success merge
# the trunk to the staging branch. It will also bump the version in the
# 'version' file with a new commit.

name: Merge to staging

on: workflow_dispatch

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: trunk
          fetch-depth: 0
      - name: Check release
        run: bash ./.github/workflows/scripts/check-release.sh
  merge_to_staging:
    needs: check_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0
      - run: |
          echo Tests OK
          echo W_E2E_TESTS_PASS=pass >> $GITHUB_ENV
      - name: Merge trunk to staging and commit updated version file
        if: env.W_E2E_TESTS_PASS == 'pass'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "RGS merge bot"
          git config user.email rgs@consttype.org
          git fetch origin trunk
          git merge origin/trunk || exit 1
          if [ -f version ];
          then
            new_version=$(perl -lpe 's/\.\K([0-9]+).*/1+$1/e' version)
            echo $new_version.0 > version
            git add version
            git commit -m 'Update version file'
            git push
          fi
