name: Merge to staging

on: workflow_dispatch

jobs:
  merge_to_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0
      - name: Merge trunk to staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "RGS merge bot"
          git config user.email rgs@consttype.org
          git fetch origin trunk
          git merge origin/trunk || exit 1
          git push
      - name: Create version file
        run: |
          git describe --tags > version
      - name: Commit version file
        uses: EndBug/add-and-commit@v7
        with:
          author_name: RGS bot
          author_email: rgs@consttype.org
          branch: staging
          cwd: "."
          message: "Update version file"
          pull: "NO-PULL"
          push: true
          signoff: false
          add: version
