name: Merge to staging

on: workflow_dispatch

jobs:
  merge_to_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 100
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "RGS merge bot"
          git config user.email rgs@consttype.org
          git fetch origin trunk
          git merge --ff-only trunk || exit 1
          git push
