# This workflow is run when a feature branch has been merged to trunk.
# It updates the manifest file at the root of the tree by adding another
# commit on trunk if needed.

name: Feature PR merged

on:
  pull_request:
    branches:
      - trunk
    types:
      - closed

jobs:
  update_manifest:
    if: github.event.pull_request.merged == true && github.head_ref != 'production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update manifest file
        run: |
          git ls-files | sort > manifest
      - id: hasChanges
        name: Checks if there are modified files
        run: |
          if [[ -z "$(git ls-files -m)" ]];
          then
            echo "No files changed"
            echo "::set-output name=changed::0"
          else
            echo "Found some files changed"
            echo "::set-output name=changed::1"
          fi
      - name: Commit manifest file
        if: ${{ steps.hasChanges.outputs.changed == 1 }}
        uses: EndBug/add-and-commit@v7
        with:
          author_name: RGS bot
          author_email: rgs@consttype.org
          branch: trunk
          cwd: "."
          message: "Update manifest"
          pull: "NO-PULL"
          push: true
          signoff: false
          add: manifest
