# This workflow is run when a feature branch has been merged to trunk.
# It updates the manifest file at the root of the tree by adding another
# commit on trunk if needed.

name: Feature PR merged

on:
  pull_request:
    branches:
      - trunk
    types:
      - closed

jobs:
  update_manifest:
    if: github.event.pull_request.merged == true && github.head_ref != 'production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update manifest file
        run: |
          pwd
          find . -type f
          git ls-files | sort > manifest
      - name: Checks if there are modified files
        id: checkModified
        uses: ./.github/workflows/composite/modified
      - name: Commit manifest file
        if: ${{ steps.checkModified.outputs.modified == 1 }}
        uses: EndBug/add-and-commit@v9
        with:
          author_name: RGS bot
          author_email: rgs@consttype.org
          message: Update manifest
          add: manifest
