# This workflow is run manually.
# It simulates a release action in github, and fast-forwards the
# production branch to the head of the staging branch.

name: Release to production

on: workflow_dispatch

jobs:
  merge_to_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
          fetch-depth: 0
      - name: Merge staging to production and tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin staging
          git merge --ff-only origin/staging || exit 1
          if [ -f version ];
          then
            git tag $(cat version)
          fi
          git push --tags origin production
