name: Release to production

on: workflow_dispatch

jobs:
  merge_to_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
          fetch-depth: 0
      - name: Merge staging to production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin staging
          git merge --ff-only origin/staging || exit 1
          git tag $(perl -lpe 's/([0-9]+)-.*/1+$1/e' version)
          git push --tags origin production
